#define COLOR0 #c1c0c0
#define COLOR1 #ff6188

#define COLOR2 #a9dc76
#define COLOR3 #ffd866

#define COLOR4 #78dce8
#define COLOR5 #ab9df2

#define COLOR6 #2aa198
#define COLOR7 #f9f8f5

#define COLOR8 #9fa097
#define COLOR9 #f92672

#define COLOR10 #a6e22e
#define COLOR11 #f4bf75

#define COLOR12 #66d9ef
#define COLOR13 #ae81ff

#define COLOR14 #2aa198
#define COLOR15 #f8f8f2

#define BASE_BACKGROUND #2d2a2e
#define BASE_FOREGROUND #fcfcfa
#define CURSOR #f8f8f2


#define SELECTED_FOREGROUND BASE_BACKGROUND
#define SELECTED_BACKGROUND COLOR3
#define SCRATCHNORM BASE_BACKGROUND
#define SCRATCHSEL SELECTED_BACKGROUND
#define HID_NORM_FG_COLOR BASE_FOREGROUND
#define HID_NORM_BG_COLOR BASE_BACKGROUND
#define HID_SEL_FG_COLOR COLOR3
#define HID_SEL_BG_COLOR BASE_BACKGROUND
#define WS_NORM_FG_COLOR BASE_FOREGROUND
#define WS_NORM_BG_COLOR BASE_BACKGROUND
#define WS_SEL_FG_COLOR SELECTED_FOREGROUND
#define WS_SEL_BG_COLOR SELECTED_BACKGROUND
#define MARKED_FG_COLOR COLOR0
#define MARKED_BG_COLOR COLOR3
#define BORDER COLOR0
#define WARNING_FG_COLOR BASE_BACKGROUND
#define WARNING_BG_COLOR COLOR11
#define URGENT_FG_COLOR COLOR15
#define URGENT_BG_COLOR COLOR9
